apiVersion: batch/v1
kind: Job
metadata:
  name: nebula-cert-ca
spec:
  template:
    spec:
      containers:
      - image: marcusjy/nebula
        name: nebula-cert-ca
        command:
        - ["nebula-cert"]
        args: ["ca", "-name", "test"]
        volumeMounts:
        - name: nebula-storage
          mountPath: "/app"
      restartPolicy: Never
      volumes:
      - name: nebula-storage
        persistentVolumeClaim:
          claimName: nebula-pvc
      