FROM --platform=${BUILDPLATFORM} debian:bookworm as builder
LABEL maintainer="Marcus Yanello <myanello@rescale.com>"

ARG TARGETARCH=arm64
ARG TARGETOS=linux
ARG NEBULA_VERSION=v1.8.0

WORKDIR /tmp

RUN apt-get update && \
  apt-get -y install wget && \
  NEBULA_ARCHIVE=nebula-$TARGETOS-$TARGETARCH.tar.gz && \
  wget https://github.com/slackhq/nebula/releases/download/$NEBULA_VERSION/$NEBULA_ARCHIVE && \
  tar -xvf $NEBULA_ARCHIVE && \
  rm -rf $NEBULA_ARCHIVE /var/lib/apt/lists/* && \
  chmod +x nebula-cert && \
  chmod +x nebula

FROM debian:bookworm

WORKDIR /app
RUN chmod 777 /app
COPY --from=builder /tmp/nebula-cert /usr/bin/nebula-cert
COPY --from=builder /tmp/nebula /usr/bin/nebula

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]