apiVersion: v1
kind: PersistentVolume
metadata:
  name: nebula-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /nfs/k8s/nebula
    server: marcus-server.lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nebula-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi