apiVersion: v1
kind: PersistentVolume
metadata:
  name: nebula-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs/k8s/nebula
    server: marcus-server.lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nebula-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nebula-core
spec:
  selector:
    name: nebula-core
  ports:
  - protocol: UDP
    port: 4242
    targetPort: 4242
---
apiVersion: v1
kind: Pod
metadata:
  name: nebula-core
spec:
  containers:
  - image: marcusjy/nebula-core
    name: nebula-core
    ports:
    - containerPort: 4242
  volumes:
  - name: nebula-storage
      claimName: nebula-pvc
---
apiVersion: v1
kind: Pod #change this to be a job
metadata:
  name: nebula-cert
spec:
  containers:
  - image: marcusjy/nebula-cert
    name: nebula-cert
  volumes:
  - name: nebula-storage
      claimName: nebula-pvc