apiVersion: v1
kind: Service
metadata:
  name: lighthouse
spec:
  selector:
    name: lighthouse
  ports:
  - protocol: UDP  # name is not required for single-port Services
    port: 4242
    targetPort: 4242
---
apiVersion: v1
kind: Pod
metadata:
  name: lighthouse
  labels:
    app: nebula
spec:
  replicas: 1
  containers:
  - image: marcusjy/lic-stat-tool
    name: check-avail
    ports:
    - containerPort: 4242
