FROM --platform=${BUILDPLATFORM} debian:bookworm as builder

ARG TARGETARCH
ARG TARGETOS
ARG NEBULA_VERSION=v1.8.0

WORKDIR /tmp

RUN apt-get update && \
  apt-get -y install wget && \
  NEBULA_ARCHIVE=nebula-$TARGETOS-$TARGETARCH.tar.gz && \
  wget https://github.com/slackhq/nebula/releases/download/$NEBULA_VERSION/$NEBULA_ARCHIVE && \
  tar -xvf $NEBULA_ARCHIVE && \
  rm -rf $NEBULA_ARCHIVE \
    ./nebula-cert \
    /var/lib/apt/lists/*

FROM debian:bookworm

WORKDIR /app

COPY --from=builder /tmp/nebula .

ENTRYPOINT ["/app/nebula"]
CMD ["-config", "/app/nebula_config.yaml"]