apiVersion: v1
kind: Service
metadata:
  name: check-avail
spec:
  selector:
    name: check-avail
  ports:
  - protocol: TCP  # name is not required for single-port Services
    port: 5001
    targetPort: 5001
---
apiVersion: v1
kind: Pod
metadata:
  name: check-avail
spec:
  containers:
  - image: marcusjy/lic-stat-tool
    name: check-avail
    ports:
    - containerPort: 5001
# ---
# apiVersion: v1
# kind: Ingress
# metadata:
#   name: check-avail
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx
#             port:
#               number: 80