FROM --platform=${BUILDPLATFORM} debian:bookworm as builder
LABEL maintainer="Marcus Yanello <myanello@rescale.com>"

ARG TARGETARCH
ARG TARGETOS
ARG NEBULA_VERSION=v1.8.0

WORKDIR /tmp

RUN apt-get update && \
  apt-get -y install wget && \
  NEBULA_ARCHIVE=nebula-$TARGETOS-$TARGETARCH.tar.gz && \
  wget https://github.com/slackhq/nebula/releases/download/$NEBULA_VERSION/$NEBULA_ARCHIVE && \
  tar -xvf $NEBULA_ARCHIVE && \
  rm -rf $NEBULA_ARCHIVE \
    ./nebula \
    /var/lib/apt/lists/*

FROM debian:bookworm

WORKDIR /app

COPY --from=builder /tmp/nebula-cert /usr/bin/nebula-cert

ENTRYPOINT ["nebula-cert"]