apiVersion: v1
kind: Pod
metadata:
  name: nebula-cert
  labels:
    app: nebula-cert
spec:
  replicas: 1
  containers:
  - image: marcusjy/nebula-cert
    name: nebula-cert
  volumes:
  - name: nebula-cert-vol
    secret:
      secretName: cert-enc-key
