FROM python:3.12.0-bookworm
LABEL maintainer="Marcus Yanello <myanello@rescale.com>"

WORKDIR /opt/
ADD ./license_utils/lmutil-latest /usr/local/bin/lmutil
ADD ./main.py /opt/
ADD ./requirements.txt /opt/

RUN apt update
RUN apt install -y lsb-release
RUN apt clean
RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install -r /opt/requirements.txt

RUN useradd -m vns3-user
USER vns3-user

EXPOSE 5001
CMD ["python3", "main.py"]
